### ISSUE TITLE
(feat): clearly define MSRV

### ISSUE THREAD

**Issue by gutenfries** [fzyzcjy/flutter_rust_bridge#1310]
# Goal:
Declare a definitive MSRV for FRB.

## Info:
The MSRV of FRB has been debated and mentioned more than a few times, however, we still have nothing better than a guess for what the actual MSRV is.

these are just a few examples:
- https://github.com/fzyzcjy/flutter_rust_bridge/discussions/588
- https://github.com/fzyzcjy/flutter_rust_bridge/pull/1306#discussion_r1279971941
- https://github.com/fzyzcjy/flutter_rust_bridge/pull/1119#issue-1620516613

## Tasks:

- [ ] Find the MSRV (https://github.com/foresterre/cargo-msrv is a wonderful tool)
- [ ] Write toolchain file for cargo (see https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file)
- [ ] Update README.md & docs accordingly
- [ ] CI test MSRV to ensure its integrity (see https://foresterre.github.io/cargo-msrv/ci/index.html)

@fzyzcjy, I'll open a PR in a bit, let me know if you have input.

**Comment by fzyzcjy** [comment]
I think so! We should explicitly have a MSRV with CI.

The cargo-msrv tool looks interesting, and your suggetion in the discussion about edition 2018 also LGTM. I will look at your experimental results about MSRV :)
