### ISSUE TITLE
Document newly added features

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#470]
For a complete list: https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/CHANGELOG.md

especially:

- [x] Support non-final fields in Dart structs #452 (thanks @surban) ----> Only link it to docs.rs, no need to write full doc
- [x] Make code generator a lib to be used in build.rs #434 (thanks @sagudev)
- [x] Add support for usize and [T;N] #442 (thanks @trobanga)
- [x] https://github.com/fzyzcjy/flutter_rust_bridge/issues/459 and its PR
- [x] Support #[frb(metadata=("freezed", "immutable" import "package:meta/meta.dart" as meta))] for structs #463
- [x] Support bridging functions with return types other than Result #335

**Comment by fzyzcjy** [comment]
Well, let me temporarily pin this before I have time (or someone has time) to update the doc, since otherwise a user of this lib will not see anywhere mentioning all these features.

**Comment by surban** [comment]
> * [ ]  Support non-final fields in Dart structs [Non-final fields in Dart structs. #452](https://github.com/fzyzcjy/flutter_rust_bridge/pull/452) (thanks @surban)

This has been documented in `frb_macros/src/lib.rs`. Actually I do prefer to have the documentation on the proc macro, viewable via docs.rs, rather than having to open a separate website to view macro documentation.

**Comment by fzyzcjy** [comment]
You are right. Then maybe I should mention this docs.rs link from our website instead of writing a full doc in the website.
