### ISSUE TITLE
(feat/bugfix): Integrate dart-sys crate

### ISSUE THREAD

**Issue by gutenfries** [fzyzcjy/flutter_rust_bridge#893]
# (feat/bugfix): Integrate dart-sys crate

## Main Goal: 

Integrate the [dart-sys](https://github.com/OptimisticPeach/dart-sys) crate directly into the repository, as well as organizing and updating much of the code.

## Related:

[Bug] Compiles with 1.51, does not compile with 1.53. #877
Delete dart_sys #890

## Tasks:

- [x] Integrate the crate directly into the repository & use as a cargo path-managed dependency
	- completed in [`599e941` (#894)](https://github.com/fzyzcjy/flutter_rust_bridge/pull/894/commits/599e941bc304ebf05acc21467ec5f1c286455d0c)
- [ ] Organize and restructure the crate, following rust best practices, in order to produce _clean_, _maintainable_, and _comprehensive_ code.
- [x] fix the issues with `build.rs` #877.
- [ ] rewrite unsafe code https://github.com/fzyzcjy/flutter_rust_bridge/pull/890#issuecomment-1351692892
- [ ] write better tests for the crate
	- [ ] Integration
	- [ ] Unit

## See Also:

[discussion on #890](https://github.com/fzyzcjy/flutter_rust_bridge/pull/890/#issuecomment-1351533716)

**Comment by gutenfries** [comment]
Linked PR: #894

**Comment by fzyzcjy** [comment]
@gutenfries Hi, feel free to edit/close the issue! As for the plan of FRB with dart-sys, cc @rogurotus who firstly integrated dart-sys :)

**Comment by gutenfries** [comment]
I will wait for a response from @rogurotus to see what is best as far as the relationship between FRB and Dart-sys :)

**Comment by rogurotus** [comment]
I'm working on making a separate crate specifically for `dart-api-dl-sys`. 
To remove the `trampoline.c` and .h dart-sdk files, as well as to remove possible conflicts when using dart-api-dl multiple times

**Comment by fzyzcjy** [comment]
IMHO, utilizing dart-sys (as @gutenfries mentions - maybe in a way with cfg flags that enable features specific for FRB), may be a good choice. For example, maybe @rogurotus's work and @gutenfries and other dart-sys maintainers' work can be combined into dart-sys? This is a bit like the scenario of https://github.com/sunshine-protocol/allo-isolate, where I have refactored and enhanced that crate (see the commit/PR history there) and then used it in frb. Dart-sys seems to be a clear boundary, so making it separately maintained looks reasonable.

But anyway these are just my two cents, and you are free to discuss and come to a conclusion for whatever you like!

**Comment by rogurotus** [comment]
If we can do it within dart-sys
it will be wonderful

**Comment by gutenfries** [comment]
Hi folks, with Dart-sys `>v3.1.8`, the `dart_api_dl` features may be enabled by enabling the `dart_api_dl` feature with cargo:

```toml
# ...
[dependencies]
# ...
dart-sys = { version = "3.1.8", features = ["dart_api_dl"] }
# ...
```

**Comment by GregoryConrad** [comment]
Is there anyway on the `dart-sys` side to make features opt-in (like in `web-sys`) so that we only pay for what we use over in FRB? I do not see why openssl should be required in a build of FRB.

**Comment by fzyzcjy** [comment]
Maybe related: https://github.com/dart-sys/dart-sys/issues/48#issuecomment-1408491046

**Comment by fzyzcjy** [comment]
> Is there anyway on the dart-sys side to make features opt-in (like how web-sys does it) so that we only pay for what we use over in FRB? I don't see why openssl (and the others causing build fails above) should be required to build FRB. This adds onto binary size which is not good for mobile app users.

Yes I totally agree it should be removed (since I believe dart-sys will not require openssl). Maybe open another issue to track this bug and @ related people btw :)

> Don't get me wrong, based on what I have read above, it seems like the dart-sys integration seems like a great next step forward. I just don't think it is quite ready yet. All features opt-in seems like a good option here, unless I am missing something.

Looks pretty reasonable. Being opt-in then we can have more time to make it mature without rough edges. And it may not be too hard to do so, given Rust's compile time flags are quite convenient.

**Comment by GregoryConrad** [comment]
Looks like 1.62.1 is passing again in my CI! Thanks for all your help @rogurotus @gutenfries @fzyzcjy

**Comment by gutenfries** [comment]
@fzyzcjy this is safe to be closed as completed

**Comment by fzyzcjy** [comment]
Great!
